Added additional checks for correct arguments.

diff --git a/new-project b/new-project
--- a/new-project
+++ b/new-project
@@ -18,20 +18,23 @@
 # Input files with the extension `.m4' are passed through GNU M4 only once.
 # Everything else is only copied.
 
-SKELDIR=~/prj/make-new-project/skel
+SKELDIR=~/prj/new-project/skel
 PROJECTDIR=~/prj
+LISTPROJECTS=0
 FORCE=0
 
-while getopts "fp:" flag; do
+while getopts "fp:l" flag; do
     case "$flag" in
         f) FORCE=1;;
         p) PROJECTDIR=$OPTARG;;
+        l) LISTPROJECTS=1;;
+        *) exit 1;;
     esac;
 done
 
-if [ $(expr $# - $OPTIND) -lt 1 ]; then
-    printf 'usage: %s [-f] [-p project-directory] language projectname\n' "$0"
-    exit 1
+if [ $LISTPROJECTS -eq 1 ]; then
+    for i in $(ls -d $SKELDIR/*); do echo ${i##*/}; done
+    exit 0
 fi
 
 if [ ! -d "$SKELDIR/${@:$OPTIND:1}" ]; then
@@ -43,6 +46,11 @@ OUTPUTNAME=$(echo ${@:$OPTIND+1:1} | \
                     tr ' ' '-' | \
                     tr "[A-Z]" "[a-z]" | \
                     tr -d -c '[:alnum:]-_.')
+
+if [ -z "$OUTPUTNAME" ]; then
+    echo "error: no project name specified."
+    exit 1
+fi
 
 # Do some basic sanity/safety checking of the command.  Tries to stop you from
 # nuking your project directories.  If you pass the `-f' flag, this stuff will
